### ISSUE TITLE
Installation fails during "npm run dev"

### ISSUE THREAD

**Issue by tariktokic** [laravel/jetstream#1231]
- Jetstream Version: 2.15.0
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.48.0
- PHP Version: 8.1.14
- 
### Description:
When installing Jetstream in new and fresh Laravel instance, vite build fails due to the usage of reserved word.
I get the following error message:

```
~/Development/MB2$ npm run dev

file://Development/MB2/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

### Steps To Reproduce:

- Install Laravel
- Install Jetstream with `php artisan jetstream:install livewire`
- run npm run dev

**Comment by tariktokic** [comment]
Solved. The problem was my ubuntu 22.04 installation with old node version "12".
