### ISSUE TITLE
cb.apply is not a function

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/jetstream#391]
- Jetstream Version: 1.5
- Jetstream Stack: Inertia 
- Laravel Version: 8.0
- PHP Version: 7.4.3
- Database Driver & Version:
- Composer Version: 2.0
- Operation system: Ubuntu 20.04
- Nodejs Version: 12.19.0
- NPM Version: 6.8.0

### Description:
On install a new project with jetstream, inertia and teams, I receive this message (see print below)

### Steps To Reproduce:
laravel new newproject8 --jet --stack=inertia --teams

![Captura de tela de 2020-10-24 15-09-03](https://user-images.githubusercontent.com/2833993/97089024-41d71c80-160b-11eb-8493-858c675b7be9.png)

**Comment by IgorDePaula** [comment]
In log file, I have:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/igor/.nvm/versions/node/v12.19.0/bin/node',
1 verbose cli   '/home/igor/.npm-global/bin/npm',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.8.0
3 info using node@v12.19.0
4 verbose npm-session d36579b85f2f6284
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall raposinha8
7 info lifecycle @~preinstall: @
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 verbose stack TypeError: cb.apply is not a function
10 verbose stack     at /home/igor/.npm-global/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:285:20
10 verbose stack     at FSReqCallback.oncomplete (fs.js:169:5)
11 verbose cwd /home/igor/projetos/raposinha8
12 verbose Linux 5.4.0-52-generic
13 verbose argv "/home/igor/.nvm/versions/node/v12.19.0/bin/node" "/home/igor/.npm-global/bin/npm" "install"
14 verbose node v12.19.0
15 verbose npm  v6.8.0
16 error cb.apply is not a function
17 verbose exit [ 1, true ]
```

**Comment by IgorDePaula** [comment]
Sorry, yarn resolve the problem.
