### ISSUE TITLE
Laravel Mix Throwing error

### ISSUE THREAD

**Issue by pranayaryal** [laravel/jetstream#611]
- Jetstream Version: ^2.0
- Jetstream Stack: Inertia
- Laravel Version: ^8.12
- PHP Version: "^7.3|^8.0"
- Database Driver & Version: mysql Ver 8.0.22-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))

### Description:
Did `laravel new {project_name}`

Then followed steps for jetstream from https://jetstream.laravel.com/2.x/installation.html

Then did `npm install`
Then `npm run watch` or `npm run dev`

But getting this error:
```
> @ watch /home/saniya/Code/public-meeting-page
> mix watch

[webpack-cli] /home/saniya/Code/public-meeting-page/node_modules/laravel-mix/src/Mix.js:18
    static _primary = null;
                    ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at NativeCompileCache._moduleCompile (/home/saniya/Code/public-meeting-page/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/saniya/Code/public-meeting-page/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/home/saniya/Code/public-meeting-page/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/home/saniya/Code/public-meeting-page/node_modules/laravel-mix/setup/webpack.config.js:2:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ watch: `mix watch`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saniya/.npm/_logs/2021-01-08T05_12_44_889Z-debug.log
```

**Comment by driesvints** [comment]
I tried it with the above steps and couldn't reproduce it.

**Comment by joaomnb** [comment]
The Node.js version is the issue – v12 or newer is required.

**Comment by pranayaryal** [comment]
Thanks @joaomnb , this worked.
