### ISSUE TITLE
I cannot find a way to integrate Storybook with Jetstream + Inertia

### ISSUE THREAD

**Issue by moracabanas** [laravel/jetstream#848]
- Jetstream Version: 2.3
- Jetstream Stack: Inertia
- Uses Teams: yes / no
- Laravel Version: 8.4.0
- PHP Version: 8.0.9
- Database Driver & Version: mysql:8.0

### Description:
Installing and running storybook gives the next error:

<details><summary>Open npm error log</summary>
<p>
`sail npm run storybook`

```log
> storybook
> start-storybook -p 6006

info @storybook/vue3 v6.3.6
info 
info => Loading presets
info => Loading 1 config file in "/var/www/html/.storybook"
info => Loading 9 other files in "/var/www/html/.storybook"
info => Adding stories defined in "/var/www/html/.storybook/main.js"
info => Using prebuilt manager
info => Using implicit CSS loaders
info => Using default Webpack4 setup
(node:1366) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
ERR! Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
ERR!   "use": [
ERR!     {
ERR!       "loader": "/var/www/html/node_modules/babel-loader/lib/index.js",
ERR!       "options": {
ERR!         "cacheDirectory": "/var/www/html/node_modules/.cache/storybook/babel",
ERR!         "sourceType": "unambiguous",
ERR!         "presets": [
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/preset-env/lib/index.js",
ERR!             {
ERR!               "shippedProposals": true,
ERR!               "loose": true
ERR!             }
ERR!           ],
ERR!           "/var/www/html/node_modules/@babel/preset-typescript/lib/index.js"
ERR!         ],
ERR!         "plugins": [
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-shorthand-properties/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-block-scoping/lib/index.js",
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/plugin-proposal-decorators/lib/index.js",
ERR!             {
ERR!               "legacy": true
ERR!             }
ERR!           ],
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
ERR!             {
ERR!               "loose": true
ERR!             }
ERR!           ],
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/plugin-proposal-private-methods/lib/index.js",
ERR!             {
ERR!               "loose": true
ERR!             }
ERR!           ],
ERR!           "/var/www/html/node_modules/@babel/plugin-proposal-export-default-from/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js",
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js",
ERR!             {
ERR!               "loose": true,
ERR!               "useBuiltIns": true
ERR!             }
ERR!           ],
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-classes/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-arrow-functions/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-parameters/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-destructuring/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-spread/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-for-of/lib/index.js",
ERR!           "/var/www/html/node_modules/@storybook/core-common/node_modules/babel-plugin-macros/dist/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-proposal-optional-chaining/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js",
ERR!           [
ERR!             "/var/www/html/node_modules/@storybook/core-common/node_modules/babel-plugin-polyfill-corejs3/lib/index.js",
ERR!             {
ERR!               "method": "usage-global",
ERR!               "absoluteImports": "/var/www/html/node_modules/core-js/index.js",
ERR!               "version": "3.16.0"
ERR!             }
ERR!           ]
ERR!         ]
ERR!       },
ERR!       "ident": "clonedRuleSet-1.use[0]"
ERR!     }
ERR!   ],
ERR!   "include": [
ERR!     "/var/www/html"
ERR!   ],
ERR!   "exclude": {}
ERR! }
ERR!     at checkResourceSource (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:167:11)
ERR!     at Function.normalizeRule (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:198:4)
ERR!     at /var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:110:20
ERR!     at Array.map (<anonymous>)
ERR!     at Function.normalizeRules (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:109:17)
ERR!     at new RuleSet (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:104:24)
ERR!     at new NormalModuleFactory (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
ERR!     at Compiler.createNormalModuleFactory (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:636:31)
ERR!     at Compiler.newCompilationParams (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:653:30)
ERR!     at Compiler.compile (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:661:23)
ERR!     at /var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
ERR!     at _next0 (eval at create (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
ERR!     at eval (eval at create (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
ERR!     at watchRunHook (/var/www/html/node_modules/webpack-virtual-modules/index.js:173:5)
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/Hook.js:154:20)
ERR!  Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
ERR!   "use": [
ERR!     {
ERR!       "loader": "/var/www/html/node_modules/babel-loader/lib/index.js",
ERR!       "options": {
ERR!         "cacheDirectory": "/var/www/html/node_modules/.cache/storybook/babel",
ERR!         "sourceType": "unambiguous",
ERR!         "presets": [
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/preset-env/lib/index.js",
ERR!             {
ERR!               "shippedProposals": true,
ERR!               "loose": true
ERR!             }
ERR!           ],
ERR!           "/var/www/html/node_modules/@babel/preset-typescript/lib/index.js"
ERR!         ],
ERR!         "plugins": [
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-shorthand-properties/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-block-scoping/lib/index.js",
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/plugin-proposal-decorators/lib/index.js",
ERR!             {
ERR!               "legacy": true
ERR!             }
ERR!           ],
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
ERR!             {
ERR!               "loose": true
ERR!             }
ERR!           ],
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/plugin-proposal-private-methods/lib/index.js",
ERR!             {
ERR!               "loose": true
ERR!             }
ERR!           ],
ERR!           "/var/www/html/node_modules/@babel/plugin-proposal-export-default-from/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js",
ERR!           [
ERR!             "/var/www/html/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js",
ERR!             {
ERR!               "loose": true,
ERR!               "useBuiltIns": true
ERR!             }
ERR!           ],
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-classes/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-arrow-functions/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-parameters/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-destructuring/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-spread/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-transform-for-of/lib/index.js",
ERR!           "/var/www/html/node_modules/@storybook/core-common/node_modules/babel-plugin-macros/dist/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-proposal-optional-chaining/lib/index.js",
ERR!           "/var/www/html/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js",
ERR!           [
ERR!             "/var/www/html/node_modules/@storybook/core-common/node_modules/babel-plugin-polyfill-corejs3/lib/index.js",
ERR!             {
ERR!               "method": "usage-global",
ERR!               "absoluteImports": "/var/www/html/node_modules/core-js/index.js",
ERR!               "version": "3.16.0"
ERR!             }
ERR!           ]
ERR!         ]
ERR!       },
ERR!       "ident": "clonedRuleSet-1.use[0]"
ERR!     }
ERR!   ],
ERR!   "include": [
ERR!     "/var/www/html"
ERR!   ],
ERR!   "exclude": {}
ERR! }
ERR!     at checkResourceSource (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:167:11)
ERR!     at Function.normalizeRule (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:198:4)
ERR!     at /var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:110:20
ERR!     at Array.map (<anonymous>)
ERR!     at Function.normalizeRules (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:109:17)
ERR!     at new RuleSet (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/RuleSet.js:104:24)
ERR!     at new NormalModuleFactory (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
ERR!     at Compiler.createNormalModuleFactory (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:636:31)
ERR!     at Compiler.newCompilationParams (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:653:30)
ERR!     at Compiler.compile (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:661:23)
ERR!     at /var/www/html/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
ERR!     at _next0 (eval at create (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
ERR!     at eval (eval at create (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
ERR!     at watchRunHook (/var/www/html/node_modules/webpack-virtual-modules/index.js:173:5)
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/Hook.js:154:20)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

</p>
</details>

Then [This link](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins) is provided to solve the issue, but even `autoprefixer` is not installed nor required by tailwind on jetstream. 

So I don't know how `main.js` storybook config should looks like. 

### Steps To Reproduce:

1. install fresh laravel with Sail
2. install jetstream with Inertia
3. install storybook with sail `sail npx sb init`
4. `sail npm run storybook`
5. postCSS error

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by moracabanas** [comment]
Just found a way to fix this so I left it here for anyone who may follow the same path:

- PostCSS addon is not included by default by Storybook in the latest versions
- Adding [@storybook/addon-postcss](https://github.com/storybookjs/addon-postcss) fix the PostCSS issue but the next step is dealing with Webpack.
- Storybook last stable release is made for Webpack 4 so it is incompatible with Wepback 5 (Laravel Jetstream + Inertia) by the following error:
`Error: Rule can only have one resource source (provided resource and test + include + exclude)`
- The solution is uninstalling Storybook and adding the [experimental Webpack 5 release](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#clean-install)

At this momment Storybook is now up and running by default configuration no need to deal with PostCSS or `main.js`

I am checking if tailwind is working properly by writting some stories 👌

**Comment by PeteJStewart** [comment]
I can confirm this worked a treat, alas tailwind isn't loading, though.
I'm sure I'll figure out why soon, and will share when I do.
@moracabanas many thanks for the solution! ;-)

**Comment by moracabanas** [comment]
@PeteJStewart I also made a project template scaffolding with Laravel Jetstream - Inertia + TailwindCSS + Storybook. 

I made it for use it with Laravel Sail, so it is optimized for containerized developement.

If you are interested feel free to use it from here.
 https://github.com/moracabanas/jetstream-storybook

You can follow a few simple steps in README.MD ti get it up and running with `npx degit`

**Comment by PeteJStewart** [comment]
Thanks!
I seemed to get it working relatively easily.
just needed to add the css to the preview.js file in .storybook

```javascript
import '../resources/css/app.css';
```
I also modified main.js

```javascript
const postcss = require('postcss')
const tailwindcss = require('../tailwind.config')
module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)",
    "../resources/js/**/*.stories.mdx",
    "../resources/js/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  "addons": [
    {
        name: '@storybook/addon-postcss',
        options: {
            postcssLoaderOptions: {
                implementation: postcss,
                postcssOptions: {
                    plugins: {
                        tailwindcss, 
                        autoprefixer: {
                        // autoprefixer options
                        },
                    },
                },
            },
        },
    },
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  "framework": "@storybook/vue3",
  "core": {
    "builder": "webpack5"
  }
}
```
